
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Provider = {
  EMAIL: 'EMAIL',
  GOOGLE: 'GOOGLE'
} as const

export type Provider = (typeof Provider)[keyof typeof Provider]


export const VerificationType = {
  CONFIRM_EMAIL: 'CONFIRM_EMAIL',
  PASSWORD_RESET: 'PASSWORD_RESET'
} as const

export type VerificationType = (typeof VerificationType)[keyof typeof VerificationType]
